spring:
  application:
    name: mysql-block-range-index-sample

# 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
  data:
    redis:
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器连接密码（默认为空）
      password: root
      # 连接超时时间
      timeout: 10000ms
      # Lettuce连接池配置
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 100
          # 连接池最大阻塞等待时间
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0

logging:
  level:
    com.zzq.mysqlblockrangeindex.sample: debug

pagehelper:
  bound-sql-interceptors: com.zzq.mysqlblockrangeindex.interceptor.PageHelperBoundSqlInterceptor


mysql-block-range-index:
  tables:
    - name: t_user
      primary-key-auto-increment-column: id
      create-time-column: create_time
